### ISSUE TITLE
AWX 19.1.0 error - winrm or requests is not installed: No module named 'winrm'

### ISSUE THREAD

**Issue by maccormac** [ansible/awx#10109]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
AWX 19.1.0 EE is missing pywinrm module resulting in failure to connect to Windows hosts

##### ENVIRONMENT
* AWX version: 19.1.0
* AWX install method: awx-operator using minikube with Docker driver
* Ansible version: 2.11.0rc2
* Operating System: Ubuntu 20.04
* Web Browser: Firefox

##### STEPS TO REPRODUCE

- Execute a job that requires ansible_connection of winrm
or
- run win_ping on AWX-EE CLI.

##### EXPECTED RESULTS

Successful connection to Windows host.

##### ACTUAL RESULTS

On CLI, win_ping fails:

bash-4.4$ ansible windows_clients -i inventory/hosts.yml -m win_ping
win10ent-test1 | FAILED! => {
    "msg": "winrm or requests is not installed: No module named 'winrm'"
}

AWX job fails with the same error when attempting to connect to Windows host.

##### ADDITIONAL INFORMATION

Excerpt of output of included pip packages - no pywinrm.

bash-4.4$ pip list
Package                            Version
---------------------------------- ------------------
pyvmomi                            7.0.2
PyYAML                             5.3.1
requests                           2.25.1

**Comment by jorgeyanesdiez** [comment]
I confirm I have the same issue with Operator 0.8.0 and 0.9.0 of AWX 19.x, so EE 0.1.x and 0.2.0

**Comment by RupinderjitGhuman** [comment]
Same issue, not working after install pywinrm

**Comment by wenottingham** [comment]
The awx-ee includes ansible.windows, but that collection does not specify pywinrm as a dependency, since the connection plugin is in ansible-core. We'd have to adjust awx-ee to build this in (or have ansible-core include it as a dependency.)

**Comment by shanemcd** [comment]
See https://github.com/ansible-collections/ansible.windows/pull/217

**Comment by pabelanger** [comment]
This was fixed in https://github.com/ansible/ansible-runner/pull/677 and I am continuing things in: https://github.com/ansible/ansible-runner/pull/686

If you try the latest awx-ee image, it should be working.

**Comment by pabelanger** [comment]
try using https://quay.io/repository/ansible/awx-ee?tab=tags the devel tag

**Comment by maccormac** [comment]
Thanks guys. Devel awx-ee tested and working.

**Comment by jurschel** [comment]
Is this going to be merged soon? Seems like a significant breaking change to have this missing.  I just got AWX running and can't use it...

**Comment by pabelanger** [comment]
@jurschel the latest release on quay.io should be working properly

**Comment by jurschel** [comment]
I got my awx install to run with the awx-ee:devel branch and it is still failing to do a simple get facts on a windows box with the following error.
{
  "msg": "winrm or requests is not installed: No module named 'winrm'",
  "_ansible_no_log": false
}

**Comment by pabelanger** [comment]
> I got my awx install to run with the awx-ee:devel branch and it is still failing to do a simple get facts on a windows box with the following error.
> {
> "msg": "winrm or requests is not installed: No module named 'winrm'",
> "_ansible_no_log": false
> }

What is the image ID?

**Comment by pabelanger** [comment]
what is the image ID?

**Comment by pabelanger** [comment]
```
$ podman run --pull always -it quay.io/ansible/awx-ee:devel pip3 freeze | grep pywinrm
pywinrm==0.4.2
```
EDIT: added always

**Comment by jurschel** [comment]
awx-ee:
    Container ID:  docker://9ae1fb6374bebda92fd413a061e2401981fc246813d7eb0141a9ccf5ad491330
    Image:         quay.io/ansible/awx-ee:devel
    Image ID:      docker-pullable://quay.io/ansible/awx-ee@sha256:ebcc73d2c239b25915afee4f8297334422398a3b21ce12192c74b85e537e8251
    Port:          <none>
    Host Port:     <none>

**Comment by jurschel** [comment]
Where should I look if it is still happening even though I show it returning the pywinrm==0.4.2 package?

**Comment by pabelanger** [comment]
make sure your ansible_python_interpreter is python3 / python3.8

**Comment by jurschel** [comment]
So do you think that the 0.2.0 release should respond with pywinrm==0.4.2?

**Comment by jurschel** [comment]
This really should be re-opened until this change is committed to a non development branch don't you think?

**Comment by jurschel** [comment]
I think the problem is that the win-rm module is being installed at /usr/local/lib/python3.8/site-packages and not in the ansible/modules.. Thoughts @pabelanger ?

ansible-playbook [core 2.11.0rc2] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.3 (default, Aug 31 2020, 16:03:14) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 2.10.3
  libyaml = True

**Comment by jurschel** [comment]
Sorry this was a miss on my part.  Even though the awx deployment was now running awx-ee:devel I hadn't added it as an execution environment.  Once I did that I got past the missing module error.

**Comment by DeLoWaN** [comment]
0.3.0 is released so there is no need to be on devel anymore.

**Comment by maccormac** [comment]
Looks like 0.3.0 includes dev version of ansible core 2.12.0.dev0?
