### ISSUE TITLE
ERROR social An account cannot be found for x@y.z

### ISSUE THREAD

**Issue by jsalatiel** [ansible/awx#11257]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

I have AWX configured to use SAML authentication against a keycloak instance. The social authentication worked for the first 8 users, but now all new users get  " ERROR [...] social An account cannot be found for user@domain"
Awx is configured to autocreate the account if it does not exist, and as I told before it worked for the first 8 users.

### AWX version

19.3.0

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

Not easy to reproduce, I have just configured SAML authentication and after a few users login just fine new users wouldn't be able to have their account provisioned.

### Expected results

New users should have their account auto provisioned.

### Actual results

ERROR    [...] social An account cannot be found for user@domain

**Comment by muchafel** [comment]
I have the same Problem, however initially with AWX 19.2.2, upgrading did not help though.
@jsalatiel: "Awx is configured to autocreate the account if it does not exist" --> imho this is the default behavoir of awx, is there a dedicated setting?

**Comment by jsalatiel** [comment]
It is the default behavior

**Comment by chrismeyersfsu** [comment]
@jsalatiel and @muchafel I think you are hitting a real bug that we might have fixed in the most recent devel (but unreleased). The good news is you can work around it. Basically, the UI is setting an unexpected default that results in `SOCIAL_AUTH_USER_FIELDS` getting set to `[]` instead of `null`.

When it's set to `null`, hard-coded sane defaults will be used but `[]` conveys not to use those hard-coded sane defaults.

You can go to `/api/v2/settings/all` and `PATCH` to set the value to `null`.

**Comment by muchafel** [comment]
Hi @chrismeyersfsu,
works! 
minor correction, as you had a typo: the endpoint is api/**v2**/settings/all/ 
Thanks a lot!

**Comment by muchafel** [comment]
I still get the error with AWX 20.1.0; fix still works, too :)

**Comment by stalk3rr** [comment]
Issue still persists in AWX 24.2.0.
Fix works, thanks @chrismeyersfsu.
And on patch also need to update SOCIAL_AUTH_OIDC_KEY that must be set with some value, we set "123".
