### ISSUE TITLE
Source update schedule web template does not render properly

### ISSUE THREAD

**Issue by leifmadsen** [ansible/awx#123]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT
 - UI

##### SUMMARY
When trying to add a schedule to update the sources hosts, the HTML template renders incorrectly.

##### ENVIRONMENT
* AWX version: master branch (Sept 11, 2017)
* Operating System: CentOS 7.3
* Web Browser: Google Chrome Unstable (latest, Fedora 26)

##### STEPS TO REPRODUCE

* Add a new inventory, save
* Click on SOURCES
* Add a new Source (shouldn't matter, I tested with Sources from a Project, saw same with an OpenStack source)
  * Setup source, credentials etc
* Click on INVENTORIES > Testing > SOURCES > Schedule future inventory syncs (calendar icon)

You'll see the HTML template is not rendering correctly.

##### EXPECTED RESULTS

It should render :)

##### ACTUAL RESULTS

```
vendor.87cae10b0bd10e13eb4b.js:399 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ vendor.87cae10b0bd10e13eb4b.js:399
vendor.87cae10b0bd10e13eb4b.js:438 TypeError: Cannot read property 'amd' of undefined
    at http://awxweb/static/js/app.87cae10b0bd10e13eb4b.js:404:439019
    at callSelect2 (http://awxweb/static/js/app.87cae10b0bd10e13eb4b.js:404:107927)
    at exports.default (http://awxweb/static/js/app.87cae10b0bd10e13eb4b.js:404:108043)
    at invoke (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:30012)
    at Object.instantiate (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:30174)
    at http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:78550
    at http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:143878
    at invokeLinkFn (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:70399)
    at nodeLinkFn (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:55720)
    at compositeLinkFn (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:45981)
    at http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:44694
    at updateView (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:148476)
    at Object.configUpdatedCallback [as configUpdated] (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:147685)
    at configureUIView (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:93424)
    at Array.forEach (<anonymous>)
    at ViewService.sync (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:93523)
    at activateViews (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:88061)
    at TransitionHook.invokeHook (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:35075)
    at TransitionHook.runSynchronousHooks (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:36258)
    at transitionSuccess (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:470:26644)
    at processQueue (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:117543)
    at http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:117810
    at Scope.$eval (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:130738)
    at Scope.$digest (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:128538)
    at Scope.$apply (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:131164)
    at done (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:85815)
    at completeRequest (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:89746)
    at XMLHttpRequest.xhr.onload (http://awxweb/static/js/vendor.87cae10b0bd10e13eb4b.js:438:90678) <div ui-view="form" class="ng-scope">
(anonymous) @ vendor.87cae10b0bd10e13eb4b.js:438
vendor.87cae10b0bd10e13eb4b.js:438 TypeError: $(...).tooltip is not a function
    at app.87cae10b0bd10e13eb4b.js:404
    at Scope.$broadcast (vendor.87cae10b0bd10e13eb4b.js:438)
    at stateChangeStartHandler (vendor.87cae10b0bd10e13eb4b.js:476)
    at TransitionHook.invokeHook (vendor.87cae10b0bd10e13eb4b.js:470)
    at TransitionHook.runSynchronousHooks (vendor.87cae10b0bd10e13eb4b.js:470)
    at Transition.run (vendor.87cae10b0bd10e13eb4b.js:470)
    at StateService.transitionTo (vendor.87cae10b0bd10e13eb4b.js:470)
    at Array.state.abstract.state.url.$urlRouterProvider.when.state._urlRule (vendor.87cae10b0bd10e13eb4b.js:470)
    at Object.invoke (vendor.87cae10b0bd10e13eb4b.js:438)
    at handleIfMatch (vendor.87cae10b0bd10e13eb4b.js:470)
    at vendor.87cae10b0bd10e13eb4b.js:470
    at check (vendor.87cae10b0bd10e13eb4b.js:470)
    at update (vendor.87cae10b0bd10e13eb4b.js:470)
    at vendor.87cae10b0bd10e13eb4b.js:470
    at vendor.87cae10b0bd10e13eb4b.js:470
    at Array.forEach (<anonymous>)
    at vendor.87cae10b0bd10e13eb4b.js:470
    at Scope.$broadcast (vendor.87cae10b0bd10e13eb4b.js:438)
    at afterLocationChange (vendor.87cae10b0bd10e13eb4b.js:438)
    at vendor.87cae10b0bd10e13eb4b.js:438
    at Scope.$eval (vendor.87cae10b0bd10e13eb4b.js:438)
    at Scope.$digest (vendor.87cae10b0bd10e13eb4b.js:438)
    at Scope.$apply (vendor.87cae10b0bd10e13eb4b.js:438)
    at done (vendor.87cae10b0bd10e13eb4b.js:438)
    at completeRequest (vendor.87cae10b0bd10e13eb4b.js:438)
    at XMLHttpRequest.xhr.onload (vendor.87cae10b0bd10e13eb4b.js:438)
(anonymous) @ vendor.87cae10b0bd10e13eb4b.js:438
vendor.87cae10b0bd10e13eb4b.js:438 TypeError: Cannot read property 'schedulerName' of undefined
    at Object.isValid (vendor.87cae10b0bd10e13eb4b.js:451)
    at vendor.87cae10b0bd10e13eb4b.js:451
    at Scope.$broadcast (vendor.87cae10b0bd10e13eb4b.js:438)
    at app.87cae10b0bd10e13eb4b.js:404
    at ChildScope.$emit (vendor.87cae10b0bd10e13eb4b.js:438)
    at app.87cae10b0bd10e13eb4b.js:404
    at Scope.$digest (vendor.87cae10b0bd10e13eb4b.js:438)
    at Scope.$apply (vendor.87cae10b0bd10e13eb4b.js:438)
    at done (vendor.87cae10b0bd10e13eb4b.js:438)
    at completeRequest (vendor.87cae10b0bd10e13eb4b.js:438)
    at XMLHttpRequest.xhr.onload (vendor.87cae10b0bd10e13eb4b.js:438)
(anonymous) @ vendor.87cae10b0bd10e13eb4b.js:438
vendor.87cae10b0bd10e13eb4b.js:438 TypeError: Cannot read property 'schedulerName' of undefined
    at Object.isValid (vendor.87cae10b0bd10e13eb4b.js:451)
    at vendor.87cae10b0bd10e13eb4b.js:451
    at Scope.$broadcast (vendor.87cae10b0bd10e13eb4b.js:438)
    at app.87cae10b0bd10e13eb4b.js:404
    at ChildScope.$emit (vendor.87cae10b0bd10e13eb4b.js:438)
    at app.87cae10b0bd10e13eb4b.js:404
    at watchGroupAction (vendor.87cae10b0bd10e13eb4b.js:438)
    at ChildScope.$eval (vendor.87cae10b0bd10e13eb4b.js:438)
    at Scope.$digest (vendor.87cae10b0bd10e13eb4b.js:438)
    at Scope.$apply (vendor.87cae10b0bd10e13eb4b.js:438)
    at done (vendor.87cae10b0bd10e13eb4b.js:438)
    at completeRequest (vendor.87cae10b0bd10e13eb4b.js:438)
    at XMLHttpRequest.xhr.onload (vendor.87cae10b0bd10e13eb4b.js:438)
(anonymous) @ vendor.87cae10b0bd10e13eb4b.js:438
```

##### ADDITIONAL INFORMATION

https://i.imgur.com/PXZOV1h.png

**Comment by mabashian** [comment]
@leifmadsen thanks for filing this!  This is a known issue and we've got a fix coming that we hope will land in the next week or so.  I'm going to close this issue for now.  We can always re-open if the problem persists after the fix lands.

**Comment by leifmadsen** [comment]
@mabashian I'm personally not a big fan of that workflow. It would be better that whatever fixes are going to fix this would reference and result in a `Closes #123` when the commit lands, which would tell me when the fix was completed, and when I should start testing again.

Also, closing this ahead of time could easily result in someone else taking a look at open issues, and then noticing their issue isn't there, and spending the time to duplicate this issue. Could we just leave this open until the fix lands?

**Comment by leifmadsen** [comment]
FYI I am unable to reproduce in latest versions. This was closed before it was fixed, but to note, it is now fixed :)

**Comment by arnarg** [comment]
Am I missing something here? I've tried tags `1.0.1`, `1` and `latest` (which are all probably the same image anyway) as well as building it myself from devel branch but I still get this bug in chrome, firefox and safari.

The inventory file is:
```
localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"

[all:vars]

dockerhub_base=ansible
dockerhub_version=1

awx_secret_key=<redacted>

postgres_data_dir=/tmp/pgdocker
host_port=80

pg_username=awx
pg_password=<redacted>
pg_database=awx
pg_port=5432
```

Console errors are:
```
TypeError: Cannot read property 'replace' of undefined
    at resolve (vendor.4c1b9c3….js:449)
    at Object.getLocal (vendor.4c1b9c3….js:449)
    at ChildScope.scope.setDefaults (vendor.4c1b9c3….js:449)
    at vendor.4c1b9c3….js:449
    at ChildScope.$emit (vendor.4c1b9c3….js:436)
    at Object.getZoneList (vendor.4c1b9c3….js:449)
    at vendor.4c1b9c3….js:449
    at app.cf519dd….js:403
    at new exports.default (app.cf519dd….js:403)
    at Object.instantiate (vendor.4c1b9c3….js:436)
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
$emit @ vendor.4c1b9c3….js:436
getZoneList @ vendor.4c1b9c3….js:449
(anonymous) @ vendor.4c1b9c3….js:449
(anonymous) @ app.cf519dd….js:403
exports.default @ app.cf519dd….js:403
instantiate @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:469
(anonymous) @ vendor.4c1b9c3….js:436
invokeLinkFn @ vendor.4c1b9c3….js:436
nodeLinkFn @ vendor.4c1b9c3….js:436
compositeLinkFn @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
updateView @ vendor.4c1b9c3….js:469
configUpdatedCallback @ vendor.4c1b9c3….js:469
configureUIView @ vendor.4c1b9c3….js:431
ViewService.sync @ vendor.4c1b9c3….js:431
activateViews @ vendor.4c1b9c3….js:469
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.invokeHook @ vendor.4c1b9c3….js:398
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.runAllHooks @ vendor.4c1b9c3….js:398
transitionSuccess @ vendor.4c1b9c3….js:398
processQueue @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
$digest @ vendor.4c1b9c3….js:436
$apply @ vendor.4c1b9c3….js:436
done @ vendor.4c1b9c3….js:436
completeRequest @ vendor.4c1b9c3….js:436
xhr.onload @ vendor.4c1b9c3….js:436

TypeError: Cannot read property 'replace' of undefined
    at resolve (vendor.4c1b9c3….js:449)
    at Object.getLocal (vendor.4c1b9c3….js:449)
    at ChildScope.scope.setDefaults (vendor.4c1b9c3….js:449)
    at Object.clear (vendor.4c1b9c3….js:449)
    at app.cf519dd….js:403
    at new exports.default (app.cf519dd….js:403)
    at Object.instantiate (vendor.4c1b9c3….js:436)
    at vendor.4c1b9c3….js:436
    at Object.<anonymous> (vendor.4c1b9c3….js:469)
    at vendor.4c1b9c3….js:436 "<div ui-view="form" class="ng-scope">"
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
invokeLinkFn @ vendor.4c1b9c3….js:436
nodeLinkFn @ vendor.4c1b9c3….js:436
compositeLinkFn @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
updateView @ vendor.4c1b9c3….js:469
configUpdatedCallback @ vendor.4c1b9c3….js:469
configureUIView @ vendor.4c1b9c3….js:431
ViewService.sync @ vendor.4c1b9c3….js:431
activateViews @ vendor.4c1b9c3….js:469
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.invokeHook @ vendor.4c1b9c3….js:398
(anonymous) @ vendor.4c1b9c3….js:398
TransitionHook.runAllHooks @ vendor.4c1b9c3….js:398
transitionSuccess @ vendor.4c1b9c3….js:398
processQueue @ vendor.4c1b9c3….js:436
(anonymous) @ vendor.4c1b9c3….js:436
$digest @ vendor.4c1b9c3….js:436
$apply @ vendor.4c1b9c3….js:436
done @ vendor.4c1b9c3….js:436
completeRequest @ vendor.4c1b9c3….js:436
xhr.onload @ vendor.4c1b9c3….js:436
```

**Comment by leifmadsen** [comment]
I just tried it again on AWX 1.0.1.120 and I can't reproduce this as I did before.

Inventories > {Pick Inventory} > Sources > Schedule future inventory syncs > Add

![image](https://user-images.githubusercontent.com/768751/32496311-d20420d4-c396-11e7-8a4e-1c53f0b9d9c7.png)
