### ISSUE TITLE
AWX receptor issue with verifysignature. 

### ISSUE THREAD

**Issue by janorn** [ansible/awx#13234]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Trying todo a healthcheck on the remote execution node after upgrading from 21.8.0 -> 21.9.0.
Got this error in the UI:
```
Remote error: ERROR: could not parse response: ERROR: could not verify signature: signature is empty
```
Did a reinstall of the remote execution node. After which it failed to start.
```
# /usr/bin/receptor -c /etc/receptor/receptor.conf
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
```
Finally i found out the root cause:
```
# grep verifysignature /etc/receptor/receptor.conf
    verifysignature:
```
Removing this config makes everything working again. Setting it to true makes the node happy but not AWX. 

### AWX version

AWX 21.9.0  

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

ansible [core 2.12.2]

### Operating system

RHEL 8.6

### Web browser

Firefox

### Steps to reproduce

Trying todo a healthcheck on the remote execution node after upgrading from 21.8.0 -> 21.9.0.
Got this error in the UI:
```
Remote error: ERROR: could not parse response: ERROR: could not verify signature: signature is empty
```
Did a reinstall of the remote execution node. After which it failed to start.
```
# /usr/bin/receptor -c /etc/receptor/receptor.conf
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
```
Finally i found out the root cause:
```
# grep verifysignature /etc/receptor/receptor.conf
    verifysignature:
```
Removing this config makes everything working again. Setting it to true makes the node happy but not AWX. 

### Expected results

Remote execution node turning up green in UI.

### Actual results

Red

### Additional information

receptor.log
```
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
Error: error loading config file: error setting field verifysignature in command work-command: value cannot be nil
```

**Comment by janorn** [comment]
This is group_vars/all.yml from the node bundle:
```yaml
receptor_user: awx
receptor_group: awx
receptor_verify: true
receptor_tls: true
receptor_work_commands:
  ansible-runner:
    command: ansible-runner
    params: worker
    allowruntimeparams: true
    verifysignature:
custom_worksign_public_keyfile: receptor/work-public-key.pem
custom_tls_certfile: receptor/tls/receptor.crt
custom_tls_keyfile: receptor/tls/receptor.key
custom_ca_certfile: receptor/tls/ca/receptor-ca.crt
receptor_protocol: 'tcp'
receptor_listener: true
receptor_port: 27199
receptor_dependencies:
  - python39-pip

podman_user: "{{ receptor_user }}"
podman_group: "{{ receptor_group }}"
```

**Comment by tanganellilore** [comment]
@janorn I notice the sma behaviour.
I opened an issue on awx-operator repo (bug is on operator side, not AWX side)  and I propose a pull request to fix this issue:
[https://github.com/ansible/awx-operator/issues/1132](https://github.com/ansible/awx-operator/issues/1132)

@AlanCoding Can you help us to implement this on AWX-operator side?

Thanks

**Comment by djyasin** [comment]
Hello,
Thank you for taking the time to bring this issue to our attention. We are actively investigating and will continue to post updates here.

**Comment by relrod** [comment]
Fixed by the above PR, this fix will go out in the next release.

**Comment by tanganellilore** [comment]
Please check the answers on https://github.com/ansible/awx-operator/issues/1132 .

Issue is still there due to awx-operator and missing `work-verification` into avx deployment
