### ISSUE TITLE
Running workflow fails if workflow has survey with message Failed to get credential types. GET status: undefined

### ISSUE THREAD

**Issue by guilhemmarchand** [ansible/awx#1672]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API
 - UI

##### SUMMARY
Running workflow systematically fails if the workflow has any survey activated, with a popup message "Failed to get credential types. GET status: undefined"

Workflows calling job templates with survey activated will fail with the same issue.

##### ENVIRONMENT
* AWX version: 1.0.4.130
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Ubuntu
* Web Browser: Chrome / Firefox

##### STEPS TO REPRODUCE

- Create a workflow
- Add any kind of survey in the workflow such as a multiple choice selection
- Add any job template (irrelevant in the issue)
- Try running the workflow

OR:

- Have a workflow that calls a template job with a survey activated
- Try running the workflow

##### EXPECTED RESULTS

- Workflow should start with no issue

##### ACTUAL RESULTS

- Popup message: "ERROR Failed to get credential types. GET status: undefined"

![image](https://user-images.githubusercontent.com/7503059/37863575-fc072d4a-2f57-11e8-86b1-06f6056753b7.png)

![image](https://user-images.githubusercontent.com/7503059/37863581-0d180c4e-2f58-11e8-9f9e-54bad97d90fa.png)

If survey is disabled, the workflow starts as it should: (unless it calls a job template that has a survey activated)

![image](https://user-images.githubusercontent.com/7503059/37863586-30ebabf8-2f58-11e8-927b-13a8adf5ead6.png)

##### ADDITIONAL INFORMATION

- If survey is disabled, then the workflow works as expected (unless the job template has a survey, in such a case the survey in the job template must be disabled to get it working)
- If the workflow is calling a job template which has a survey, the issue appears as long as the survey is not disabled in the job template
- Everything was working fine until very recently (a week ago)
- Templates jobs themselves with survey work fine, only Workflows are affected

**Comment by steefenh** [comment]
@guilhemmarchand 👍  good analysis and description.
Can confirm this behaviour.

**Comment by aviam** [comment]
same bug on my env too,
AWX version: latest
AWX install method: docker on linux
Ansible version: 2.5.0
Operating System: Ubuntu
Web Browser: Chrome / Firefox

**Comment by aviam** [comment]
any estimation when this bug will solved?

**Comment by amapi** [comment]
As workflow are broken witth survey, can we have some kind of ETA  ?

**Comment by guilhemmarchand** [comment]
Yes this bug is very annoying and breaks any workflow with survey, would be nice to have some visibility ?

**Comment by guilhemmarchand** [comment]
Hello, would there be any news about this issue ?

**Comment by shakirabanu** [comment]
My existing workflows are broken now due to this bug.. Please provide ETA

**Comment by RichNahra** [comment]
same here

**Comment by ryanpetrello** [comment]
this should be resolved now via 3dd9ca3

**Comment by earchibald-lv** [comment]
I did a new build with your fix, @ryanpetrello, and it's still throwing the same problem.

**Comment by earchibald-lv** [comment]
@ryanpetrello - Hey, this 'fix' is not functional in my build of 1.0.6.0. Still throwing the error any my workflow is unusable. Any ideas?

**Comment by earchibald-lv** [comment]
Every single thing documented above is still occurring under 1.0.6.0.

**Comment by earchibald-lv** [comment]
@guilhemmarchand, @shakirabanu , @amapi, @steefenh, @aviam --- are you still running into this?

**Comment by aviam** [comment]
Yes

**Comment by mabashian** [comment]
@earchibald-lv following your steps I'm not able to reproduce the bug.  If possible, can you include a screenshot of the browser's console?  There should a javascript error in there that may help me understand what the issue is.

**Comment by greenscar** [comment]
1.0.5.32; no javascript errors on my side when I hit this same problem

I create a job template with a survey & it works fine. I create a workflow with a survey and I get this error.


Network traffic from browser:
*launch/*
response: 
```
{
    "can_start_without_user_input":false,
    "survey_enabled":true,
    "variables_needed_to_start":["answervar"],
    "node_templates_missing":[],
    "node_prompts_rejected":[],
    "workflow_job_template_data":
    {
        "id":38,
        "description":"",
        "name":"testwf"
    }
}
```
*launch/*
response:
```
{
"name":"Workflow Job Template Launch",
"description":"Launch a Workflow Job Template:\n\nMake a GET request to this resource to determine if the workflow_job_template\ncan be launched and whether any passwords are required to launch the\nworkflow_job_template. The response will include the following fields:\n\n* `can_start_without_user_input`: Flag indicating if the workflow_job_template\n  can be launched without user-input (boolean, read-only)\n* `variables_needed_to_start`: Required variable names required to launch the\n  workflow_job_template (array, read-only)\n* `survey_enabled`: Flag indicating whether the workflow_job_template has an\n  enabled survey (boolean, read-only)\n* `extra_vars`: Text which is the `extra_vars` field of this workflow_job_template\n  (text, read-only)\n* `node_templates_missing`: List of node ids of all nodes that have a\n  null `unified_job_template`, which will cause their branches to stop\n  execution (list, read-only)\n* `node_prompts_rejected`: List of node ids of all nodes that have\n  specified a field that will be rejected because its  `unified_job_template`\n  does not allow prompting for this field, this will not halt execution of\n  the branch but the field will be ignored (list, read-only)\n* `workflow_job_template_data`: JSON object listing general information of\n  this workflow_job_template (JSON object, read-only)\n\nMake a POST request to this resource to launch the workflow_job_template. If any\ncredential, inventory, project or extra variables (extra_vars) are required, they\nmust be passed via POST data, with extra_vars given as a YAML or JSON string and\nescaped parentheses.\n\nIf successful, the response status code will be 201.  If any required passwords\nare not provided, a 400 status code will be returned.  If the workflow job cannot\nbe launched, a 405 status code will be returned. If the provided credential or\ninventory are not allowed to be used by the user, then a 403 status code will\nbe returned.",
"renders":["application/json",
"text/html"],
"parses":["application/json"],
"actions":
{
    "POST":
    {
        "extra_vars":
        {
            "type":"field",
            "required":false,"label":"Extra vars",
            "write_only":true
        }
    },
    "GET":
    {
        "can_start_without_user_input":
        {
            "type":"boolean",
            "label":"Can start without user input"
        }
        ,"survey_enabled":
        {
            "type":"field",
            "label":"Survey enabled"
        },
        "variables_needed_to_start":
        {
            "type":"field",
            "label":"Variables needed to start"
        },
        "node_templates_missing":
        {
            "type":"field",
            "label":"Node templates missing"
        },
        "node_prompts_rejected":
        {
            "type":"field",
            "label":"Node prompts rejected"
        },
        "workflow_job_template_data":
        {
            "type":"field",
            "label":"Workflow job template data"
        }
    }
    },
"types":["workflow_job_template"]
}
```

*survey_spec/*
response:

```
{
"name":"Workflow Job Template Launch",
"description":"Launch a Workflow Job Template:\n\nMake a GET request to this resource to determine if the workflow_job_template\ncan be launched and whether any passwords are required to launch the\nworkflow_job_template. The response will include the following fields:\n\n* `can_start_without_user_input`: Flag indicating if the workflow_job_template\n  can be launched without user-input (boolean, read-only)\n* `variables_needed_to_start`: Required variable names required to launch the\n  workflow_job_template (array, read-only)\n* `survey_enabled`: Flag indicating whether the workflow_job_template has an\n  enabled survey (boolean, read-only)\n* `extra_vars`: Text which is the `extra_vars` field of this workflow_job_template\n  (text, read-only)\n* `node_templates_missing`: List of node ids of all nodes that have a\n  null `unified_job_template`, which will cause their branches to stop\n  execution (list, read-only)\n* `node_prompts_rejected`: List of node ids of all nodes that have\n  specified a field that will be rejected because its  `unified_job_template`\n  does not allow prompting for this field, this will not halt execution of\n  the branch but the field will be ignored (list, read-only)\n* `workflow_job_template_data`: JSON object listing general information of\n  this workflow_job_template (JSON object, read-only)\n\nMake a POST request to this resource to launch the workflow_job_template. If any\ncredential, inventory, project or extra variables (extra_vars) are required, they\nmust be passed via POST data, with extra_vars given as a YAML or JSON string and\nescaped parentheses.\n\nIf successful, the response status code will be 201.  If any required passwords\nare not provided, a 400 status code will be returned.  If the workflow job cannot\nbe launched, a 405 status code will be returned. If the provided credential or\ninventory are not allowed to be used by the user, then a 403 status code will\nbe returned.",
"renders":["application/json",
"text/html"],
"parses":["application/json"],
"actions":
{
    "POST":
    {
        "extra_vars":
        {
            "type":"field",
            "required":false,"label":"Extra vars",
            "write_only":true
        }
    },
    "GET":
    {
        "can_start_without_user_input":
        {
            "type":"boolean",
            "label":"Can start without user input"
        }
        ,"survey_enabled":
        {
            "type":"field",
            "label":"Survey enabled"
        },
        "variables_needed_to_start":
        {
            "type":"field",
            "label":"Variables needed to start"
        },
        "node_templates_missing":
        {
            "type":"field",
            "label":"Node templates missing"
        },
        "node_prompts_rejected":
        {
            "type":"field",
            "label":"Node prompts rejected"
        },
        "workflow_job_template_data":
        {
            "type":"field",
            "label":"Workflow job template data"
        }
    }
    },
"types":["workflow_job_template"]
}
```


*credential_types/*
response: cred type json
