### ISSUE TITLE
Job Results display variables - {{ inventory_scope_name }}

### ISSUE THREAD

**Issue by prashanthrajagopal** [ansible/awx#1726]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY
All job results(the left pane) display the variable names and not values for variables(screenshot attached).
Stdout also does not come up.
[https://github.com/ansible/awx/issues/1724](url)
<img width="640" alt="screen shot 2018-04-04 at 4 54 27 pm" src="https://user-images.githubusercontent.com/1052771/38305249-d554191c-3829-11e8-8c28-82959822541a.png">
<img width="1919" alt="screen shot 2018-04-04 at 5 09 37 pm" src="https://user-images.githubusercontent.com/1052771/38305598-0724c4e0-382b-11e8-8d15-daab12f3f7e1.png">

##### ENVIRONMENT
* AWX version: 1.0.5
* AWX install method: docker on linux
* Ansible version:  2.5.0
* Operating System: Ubuntu 16.04
* Web Browser: Chrome 53

##### STEPS TO REPRODUCE
Just open any job that has executed

##### ACTUAL RESULTS
<img width="640" alt="screen shot 2018-04-04 at 4 54 27 pm" src="https://user-images.githubusercontent.com/1052771/38305249-d554191c-3829-11e8-8c28-82959822541a.png">

**Comment by ryanpetrello** [comment]
Hey @prashanthrajagopal,

This is a known issue that was recently fixed in awx: https://github.com/ansible/awx/issues/1700
Please try upgrading.

**Comment by prashanthrajagopal** [comment]
Thanks. That works.. 
The STDOUT is still not visible.. I see that has been raised in another issue.
