### ISSUE TITLE
awx-manage print_settings traceback with awx_1.0.5.11 build

### ISSUE THREAD

**Issue by akcrisp** [ansible/awx#1748]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - API

 - Installer

##### SUMMARY
running the command  (in awx_task container) -  "awx-manage print_settings"

crashes out with errors -

2018-04-10 13:09:00,615 WARNING  awx.conf.settings The current value "u'MemberDNGroupType'" for setting "AUTH_LDAP_1_GROUP_TYPE" is invalid.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 372, in _get_local
    return field.run_validation(value)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 523, in run_validation
    value = self.to_internal_value(data)
  File "/usr/lib/python2.7/site-packages/awx/sso/fields.py", line 401, in to_internal_value
    return cls(**params_sanitized)
TypeError: __init__() takes at least 2 arguments (2 given)
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.5.11', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_extensions/management/commands/print_settings.py", line 49, in handle
    value = getattr(settings, attr)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 479, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 395, in __getattr__
    return self._get_default(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 382, in _get_default
    return getattr(self.default_settings, name)
AttributeError: 'Settings' object has no attribute 'AUTH_LDAP_1_GROUP_TYPE'

##### ENVIRONMENT
* AWX version: 1.0.5.11
* AWX install method:  docker on linux, 
* Ansible version:  2.5.0
* Operating System: RHEL 7.4
* Web Browser: Chrome 10

##### STEPS TO REPRODUCE

run bash in awx_task container

run command awx-manage print_settings

##### EXPECTED RESULTS

output of awx settings

##### ACTUAL RESULTS

2018-04-10 13:09:00,615 WARNING  awx.conf.settings The current value "u'MemberDNGroupType'" for setting "AUTH_LDAP_1_GROUP_TYPE" is invalid.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 372, in _get_local
    return field.run_validation(value)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 523, in run_validation
    value = self.to_internal_value(data)
  File "/usr/lib/python2.7/site-packages/awx/sso/fields.py", line 401, in to_internal_value
    return cls(**params_sanitized)
TypeError: __init__() takes at least 2 arguments (2 given)
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.5.11', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_extensions/management/commands/print_settings.py", line 49, in handle
    value = getattr(settings, attr)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 479, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 395, in __getattr__
    return self._get_default(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 382, in _get_default
    return getattr(self.default_settings, name)
AttributeError: 'Settings' object has no attribute 'AUTH_LDAP_1_GROUP_TYPE'

##### ADDITIONAL INFORMATION

Looking in the api - we haven't got the AUTH_LDAP_1 settings defined ( we do have AUTH_LDAP) -

 "AUTH_LDAP_1_SERVER_URI": "",
    "AUTH_LDAP_1_BIND_DN": "",
    "AUTH_LDAP_1_BIND_PASSWORD": "",
    "AUTH_LDAP_1_START_TLS": false,
    "AUTH_LDAP_1_CONNECTION_OPTIONS": {
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_1_USER_SEARCH": [],
    "AUTH_LDAP_1_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_1_USER_ATTR_MAP": {},
    "AUTH_LDAP_1_GROUP_SEARCH": [],
    "AUTH_LDAP_1_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_1_GROUP_TYPE_PARAMS": {
        "name_attr": "cn"
    },
    "AUTH_LDAP_1_REQUIRE_GROUP": null,
    "AUTH_LDAP_1_DENY_GROUP": null,
    "AUTH_LDAP_1_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_1_ORGANIZATION_MAP": {},
    "AUTH_LDAP_1_TEAM_MAP": {},
    "AUTH_LDAP_2_SERVER_URI": "",
    "AUTH_LDAP_2_BIND_DN": "",
    "AUTH_LDAP_2_BIND_PASSWORD": "",
    "AUTH_LDAP_2_START_TLS": false,
    "AUTH_LDAP_2_CONNECTION_OPTIONS": {
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_2_USER_SEARCH": [],
    "AUTH_LDAP_2_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_2_USER_ATTR_MAP": {},
    "AUTH_LDAP_2_GROUP_SEARCH": [],
    "AUTH_LDAP_2_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_2_GROUP_TYPE_PARAMS": {
        "name_attr": "cn"
    },
    "AUTH_LDAP_2_REQUIRE_GROUP": null,
    "AUTH_LDAP_2_DENY_GROUP": null,
    "AUTH_LDAP_2_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_2_ORGANIZATION_MAP": {},
    "AUTH_LDAP_2_TEAM_MAP": {},
    "AUTH_LDAP_3_SERVER_URI": "",
    "AUTH_LDAP_3_BIND_DN": "",
    "AUTH_LDAP_3_BIND_PASSWORD": "",
    "AUTH_LDAP_3_START_TLS": false,
    "AUTH_LDAP_3_CONNECTION_OPTIONS": {
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_3_USER_SEARCH": [],
    "AUTH_LDAP_3_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_3_USER_ATTR_MAP": {},
    "AUTH_LDAP_3_GROUP_SEARCH": [],
    "AUTH_LDAP_3_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_3_GROUP_TYPE_PARAMS": {
        "name_attr": "cn"
    },
    "AUTH_LDAP_3_REQUIRE_GROUP": null,
    "AUTH_LDAP_3_DENY_GROUP": null,
    "AUTH_LDAP_3_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_3_ORGANIZATION_MAP": {},
    "AUTH_LDAP_3_TEAM_MAP": {},
    "AUTH_LDAP_4_SERVER_URI": "",
    "AUTH_LDAP_4_BIND_DN": "",
    "AUTH_LDAP_4_BIND_PASSWORD": "",
    "AUTH_LDAP_4_START_TLS": false,
    "AUTH_LDAP_4_CONNECTION_OPTIONS": {
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_4_USER_SEARCH": [],
    "AUTH_LDAP_4_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_4_USER_ATTR_MAP": {},
    "AUTH_LDAP_4_GROUP_SEARCH": [],
    "AUTH_LDAP_4_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_4_GROUP_TYPE_PARAMS": {
        "name_attr": "cn"
    },
    "AUTH_LDAP_4_REQUIRE_GROUP": null,
    "AUTH_LDAP_4_DENY_GROUP": null,
    "AUTH_LDAP_4_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_4_ORGANIZATION_MAP": {},
    "AUTH_LDAP_4_TEAM_MAP": {},
    "AUTH_LDAP_5_SERVER_URI": "",
    "AUTH_LDAP_5_BIND_DN": "",
    "AUTH_LDAP_5_BIND_PASSWORD": "",
    "AUTH_LDAP_5_START_TLS": false,
    "AUTH_LDAP_5_CONNECTION_OPTIONS": {
        "OPT_NETWORK_TIMEOUT": 30,
        "OPT_REFERRALS": 0
    },
    "AUTH_LDAP_5_USER_SEARCH": [],
    "AUTH_LDAP_5_USER_DN_TEMPLATE": null,
    "AUTH_LDAP_5_USER_ATTR_MAP": {},
    "AUTH_LDAP_5_GROUP_SEARCH": [],
    "AUTH_LDAP_5_GROUP_TYPE": "MemberDNGroupType",
    "AUTH_LDAP_5_GROUP_TYPE_PARAMS": {
        "name_attr": "cn"
    },
    "AUTH_LDAP_5_REQUIRE_GROUP": null,
    "AUTH_LDAP_5_DENY_GROUP": null,
    "AUTH_LDAP_5_USER_FLAGS_BY_GROUP": {},
    "AUTH_LDAP_5_ORGANIZATION_MAP": {},
    "AUTH_LDAP_5_TEAM_MAP": {}
}

**Comment by akcrisp** [comment]
Just bit more background - I am using this to get the settings so I can backup the db. Therefore its a fairly important...

**Comment by ryanpetrello** [comment]
@akcrisp this should be resolved now via https://github.com/ansible/awx/commit/00cd6cb384d5ad8776f24684bdb09beb57e86517

Mind giving it a try?

**Comment by akcrisp** [comment]
Sure will do - Monday

**Comment by akcrisp** [comment]
This is not fixed.  This still occurs with the latest build (AWX 1.0.5.32) 
Running ansible version 2.5.2-1

getting -

 docker exec -ti awx_task bash
[root@awx awx]# awx-manage print_settings | grep '^DATABASES'
2018-04-30 07:10:36,053 WARNING  awx.conf.settings The current value "u'MemberDNGroupType'" for setting "AUTH_LDAP_1_GROUP_TYPE" is invalid.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 372, in _get_local
    return field.run_validation(value)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/rest_framework/fields.py", line 523, in run_validation
    value = self.to_internal_value(data)
  File "/usr/lib/python2.7/site-packages/awx/sso/fields.py", line 401, in to_internal_value
    return cls(**params_sanitized)
TypeError: __init__() takes at least 2 arguments (2 given)
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==1.0.5.32', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django_extensions/management/commands/print_settings.py", line 49, in handle
    value = getattr(settings, attr)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 479, in __getattr_without_cache__
    return getattr(self._wrapped, name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 395, in __getattr__
    return self._get_default(name)
  File "/usr/lib/python2.7/site-packages/awx/conf/settings.py", line 382, in _get_default
    return getattr(self.default_settings, name)
AttributeError: 'Settings' object has no attribute 'AUTH_LDAP_1_GROUP_TYPE'
