### ISSUE TITLE
Inventory source sync schedule broken

### ISSUE THREAD

**Issue by jniewt** [ansible/awx#1850]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When `schedule inventory syncs` is pressed for an inventory source from a custom script, the cog wheel and "working" message pops up for a second and disappears without doing anything in the UI.

##### ENVIRONMENT
* AWX version: 1.0.6.3
* AWX install method: docker on linux
* Ansible version:  2.5.2
* Operating System: Debian 9
* Web Browser: Chrome (latest version)

##### STEPS TO REPRODUCE

Go to inventory that has a custom script as a source, click on sources, click on `schedule inventory syncs` next to the source with custom script.

##### EXPECTED RESULTS

A page appears with list of schedules and possibility of adding schedules. Like the one for project schedules.

##### ACTUAL RESULTS

The cog wheel and "working" message pops up for a second and nothing happens.

**Comment by wkleinhenz** [comment]
I have the same problem I believe it may be related to the use of an nginx proxy for ssl
My build is using docker on Centos 7 with the latest version
also seems to effect the ability to view job status/results

**Comment by jaredevantabor** [comment]
this is fixed in devel now.

**Comment by jhpandu** [comment]
How to fix this inventory sync schedule issue?

**Comment by jniewt** [comment]
@jaredevantabor Just updated to 1.0.6.11 and the issue is still there for me.

**Comment by steflaf** [comment]
@jaredevantabor same for me in 1.0.6.11

**Comment by jaredevantabor** [comment]
@jniewt can you tell me if you are seeing any console errors? I just tested again in AWX to confirm, and I'm not having any problems scheduling inventory syncs: 

![image](https://user-images.githubusercontent.com/7010629/40683851-93bd949c-6344-11e8-9f72-1204a1df58ba.png)


I'm currently on AWX: 1.0.6.11. Could you try clearing your cache and trying again?

**Comment by jhpandu** [comment]
It worked for me in AWX version -1.0.6.14. But looks like it's not working in mozilla. It worked only in chrome browser for me.

**Comment by jniewt** [comment]
@jaredevantabor Sorry for the late answer, I wasn't seeing notifications from github. Clearing the cache fixed the issue.

**Comment by seniormuffinman** [comment]
@jniewt sorry for the probably dumb question, but what cache are you talking about and how do you clean it?

**Comment by jniewt** [comment]
@seniormuffinman The browser cache. E.g. in chrome you can go into settings and search for clear browsing data. There you can clear it.

**Comment by seniormuffinman** [comment]
Lol, thanks! I thought you were talking about something awx-specific.
Tried that, didn't work tho. I saw an issue was raised earlier this week.
