### ISSUE TITLE
Cannot launch jobs when inventory prompt on launch is selected in template

### ISSUE THREAD

**Issue by jaevans** [ansible/awx#1860]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY

Unable to launch jobs when inventory "Prompt on Launch" is selected.

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method:  docker on linux
* Ansible version:  2.5.2
* Operating System: RHEL 7.4
* Web Browser: Chrome, Firefox

##### STEPS TO REPRODUCE

1. Create Job Template from job, select PROMPT ON LAUNCH for inventory. Selecting a default inventory or not does not change results.
2. Attempt to launch a job using the template
3. The select inventory prompt opens, but the next button is grayed out and cannot be selected.

##### EXPECTED RESULTS

Able to move to the next step of the wizard.

##### ACTUAL RESULTS

Unable to move to the next step via the next button or the step buttons as the top of the window.

##### ADDITIONAL INFORMATION

All testing was done from Mac OS, latest chrome and firefox. The same behavior was observed in the 1.0.6.3 containers.

**Comment by cpatry-poly** [comment]
Duplicate of https://github.com/ansible/awx/issues/1824 :-) .

**Comment by jaevans** [comment]
I see that #1824 is closed (which is why I missed it) but the code hasn't been merged yet. @jakemcdermott, you closed the other issue, but without the merge, we're still considering this a show-stopper for our usage of 1.0.6, and we can't go back to 1.0.5 because of other issues. Iis there a plan for merging the code in the near future?

**Comment by jaredevantabor** [comment]
The code has been merged into devel and this should be fixed now.

**Comment by balaramr** [comment]
@jaredevantabor, I have tired your devel code still cannot launch jobs when inventory prompt on launch

**Comment by cpatry-poly** [comment]
@balaramr : we had this issue too and the release 1.0.6 definitively fix this for us.
We use docker image 1.0.6.9 in production and we have a lot of job templates with inventory prompt on launch.

**Comment by balaramr** [comment]
Hello, Can you share docker images please
________________________________

**Comment by cpatry-poly** [comment]
They are on dockerhub : https://hub.docker.com/r/ansible/awx_web/tags/ + https://hub.docker.com/r/ansible/awx_task/tags/

**Comment by jaredevantabor** [comment]
@balaramr I would also recommend clearing your cache and reloading the UI, as files can get cached by your browser. Are you seeing any console errors?

**Comment by balaramr** [comment]
Thannk you @Jared Tabor<mailto:notifications@github.com>

**Comment by balaramr** [comment]
Thank you @ Christian Patry AWX 1.0.6.9 worked like a charm…
