### ISSUE TITLE
Users permissions discarderd when "SCM project" get latest version

### ISSUE THREAD

**Issue by agentili** [ansible/awx#1868]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Teams and users permissions in a "SCM type" project are removed when get latest SCM version

##### ENVIRONMENT
* AWX version: 1.0.6.5
* AWX install method: docker-compose on linux
* Ansible version:  2.5.2
* Operating System: Ubuntu 16.04
* Web Browser: Chrome

##### STEPS TO REPRODUCE

- Add project with SCM source
- Create a team with one user (e.g. "testuser")
- Assign permissions on SCM project (use & update) to that team
- Login as "testuser"
- Get latest SCM version of project

##### EXPECTED RESULTS

Project disappear after refresh of the page

##### ACTUAL RESULTS

SCM project is no more visible in the "testuser" screen

**Comment by cpatry-poly** [comment]
Hi !
We had the same issue, so we rollback to version 1.0.5.

**Comment by AlanCoding** [comment]
This is fixed in the current source tree now.

**Comment by madeinoz67** [comment]
I'm still seeing permission type errors in latest development docker 1.0.6.8 image when trying to add any type of object to a LDAP managed team.  This includes local users, credentials, tasks, inventories etc

![2018-05-21_20-06-29](https://user-images.githubusercontent.com/4160293/40306845-ca135e0e-5d32-11e8-893b-d1ce1ddf4a82.png)

**Comment by AlanCoding** [comment]
That looks more similar to https://github.com/ansible/awx/issues/1856, and given your experience, it may not be a duplicate after all.

The specific root cause in this issue was identified and fixed. We may need to re-open that other one.

specifically, the fix to this problem landed in

949895d0bc8367dc029fc6e94448d2495fe94ade

That caused an issue irrelevant of whether LDAP was used or not.

**Comment by madeinoz67** [comment]
yes I agree, what I'm seeing is almost identical to #1856 and have just tested with manual created users/teams to same results.  
  
I'm assuming the fix mentioned above is in current 1.0.6.8 build on docker hub.

**Comment by agentili** [comment]
This bug, following "steps to reproduce" listed in the first post, **is solved**
Thanks
