### ISSUE TITLE
Job output not displayed

### ISSUE THREAD

**Issue by trim777** [ansible/awx#2354]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

After launch job there are no output displayed in job log. Ansible awx started as stack in swarm. If I restart awx-task container - everything becomes OK, I can see output from new started jobs and for previous launches too.
##### ENVIRONMENT
* AWX version: 1.0.8.0
* AWX install method: docker swarm on linux
* Ansible version:  2.6.4
* Operating System: Ubuntu desktop 18.04
* Web Browser: Chrome 68.0.3440

**Comment by jakemcdermott** [comment]
Hi trim777, can you provide logs from the task container when the issue occurs?

Also, when it is occurring, is it just job output or all real-time updates? (job statuses on other pages, etc.).

When you're seeing the error, can you see output from previous launches?

This information might help us narrow this down.

**Comment by jakemcdermott** [comment]
Also, which AWX installation method (specific playbook and role from the awx repo [installer](https://github.com/ansible/awx/tree/devel/installer) ) are you using?

**Comment by trim777** [comment]
Hi! Thank you for response =)
> Hi trim777, can you provide logs from the task container when the issue occurs?

Log from task container: 
https://pastebin.com/nRS1LZJG

>Also, when it is occurring, is it just job output or all real-time updates? (job statuses on other pages, etc.).

This issue related to jobs already passed and to jobs which I manually started and would like to see execution progress. And this issue is only about inivisible log, all other things are visible: https://imgur.com/qmIYGPb

> When you're seeing the error, can you see output from previous launches?

Yes, some another launches are visible ( I mean visible their logs), they were created after starting AWX

> Also, which AWX installation method (specific playbook and role from the awx repo installer ) are you using?

I used this method: I installed on my desktop AWX stack with option for creating docker-compose file. After testing AWX on my desktop I rsynced docker-compose file and postgres volume on docker-swarm cluster, and started stack from that docker-compose file with mounted postgres volume.

**Comment by trim777** [comment]
I updated awx_web and awx_task docker images to latest 2.0 release - that didn't solve the issue and now there is another issue (I think I saw this issue in another bug) with displaying workflows:
https://imgur.com/a/8BRf6XB

**Comment by FlorianKuckelkorn** [comment]
I am experiencing the same issue here, for the workflow display and for the log retrival. Restarting the container does help for a short amount of time, please fix fast :)

**Comment by matburt** [comment]
I believe we've fixed these issues under the 2.X AWX release, please try it there and let us know how things go.

**Comment by srgvg** [comment]
I still experience this issue on 2.x

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/awx-project/3CLj0HUFoR4

I recently migrated to AWX 2.1.0, but this problem has been showing itself intermittently before, too (running 1.7.something).

Occasionally, jobs run, but show no output in the web interface. At some time, while it was running, I checked the process list in the task containers, and could recognise it was effectively running.
At some one time, I scaled down to 1 pod - we usually run 3 pods - then scaled to 0, and back to 1, and jobs started to show output again. Some time later scaling again to three pods, triggered the issue of not showing any output, again.
When I checked the job output text files on disk, they were also just empty files.
I was out-of-office two days, and this morning checking our setup, I notice latest jobs have output shown again.
Looking online, I only find references to these kind of issues, in old bug reports that AFAICS should be solved by now.
 I know this is not plain stdout, but the result of a special callback in AWX. But as this "seems" to happen intermittently, and I can't pin-point a certain trigger or exact circumstance where this happens, I'm not sure where to go from here.

How can i troubleshoot this, when it happens? What are the mechanisms that may fail here?

**Comment by LukeDRussell** [comment]
We're running 2.1.2 and experience the same, intermittent problem of stdout not being rendered in the ui. In my experience tower-cli renders stdout correctly. 

Edit: Redeploying the project (in OKD / Openshift) will generally bring back the stdout rendering in the web ui.

**Comment by AechLyons** [comment]
Also experiencing this AWX 9.2.0 (via docker deployment) with postgres database running on its own

**Comment by AechLyons** [comment]
I'll try restarting the awx_task container

**Comment by Idanatcox** [comment]
We are seeing this issue on 9.1.1 happens intermittently

**Comment by silverscreen** [comment]
I hate to chime in on a closed issue but I can see others have continued to experience this and I don't see any resolution for it. I've only just encountered this problem myself with AWX 16.0.0 within a Kubernetes installation. I have never encountered this issue whenever I've ran it locally in Docker.

The symptoms I'm having is job output is not automatically generated inside my browser unless I refresh the page.
Did anyone find a resolution to this? I'm at a total loss - any help would be greatly appreciated.

**Comment by dossjjx** [comment]
Now seeing this on 17.0.0, though output is shown **after** the job completes. Recently upgraded from 9.3.0 to 17.0.0 and seeing this issue after upgrade.

**Comment by ronik010** [comment]
> Now seeing this on 17.0.0, though output is shown **after** the job completes. Recently upgraded from 9.3.0 to 17.0.0 and seeing this issue after upgrade.

I confirm the problem. Updated from 2.0.1 to 16, and then to 17 and the problem appeared

**Comment by abdel-ops** [comment]
hello ,
i confirm i face the same issue since i've upgraded to 17 , the job output is not displayed , i suspect an issue with the websocket connection.

**Comment by dossjjx** [comment]
Below is console output from the developer tools in Chrome and the useWebsocket.js file that seems to error out. Same issue occurring on Firefox as well. AWX 17.0

![image](https://user-images.githubusercontent.com/35515947/106099115-c7cd9c80-60ff-11eb-88c3-7baccc777433.png)

![image](https://user-images.githubusercontent.com/35515947/106099546-78d43700-6100-11eb-839c-19392a4a4b61.png)

**Comment by ryanpetrello** [comment]
@jakemcdermott does @dossjj's comment look like it's related to https://github.com/ansible/awx/issues/8596 ?

**Comment by dossjjx** [comment]
> @jakemcdermott does @dossjj's comment look like it's related to #8596 ?

Yes looks like it. Created a new issue for this and it was closed because #8596 is actively working on it. Devs mentioned this should be fixed in the next release.

**Comment by aem12f** [comment]
I have upgraded to latest awx tag: 17.1.0, using local_docker installation, and still am experiencing this issue

**Comment by edvinas31** [comment]
Started to face same issue

**Comment by bdoublet91** [comment]
Hi,
Maybe a up here

Happens sometimes when AWX container runs for a long time, no logs at all when I execute the jobs
The job starts, executes and finished successfully but no logs on UI and when I download the file ^^
![image](https://user-images.githubusercontent.com/57101863/154981730-2f1ae507-d723-45fd-bd1b-f6a27ac00f70.png)

Supervisorctl status get all process up
awx
```bash
supervisorctl -c /etc/supervisord.conf status
awx-config-watcher               RUNNING   pid 82, uptime 14 days, 0:47:44
tower-processes:awx-rsyslogd     RUNNING   pid 150, uptime 14 days, 0:47:01
tower-processes:daphne           RUNNING   pid 85, uptime 14 days, 0:47:44
tower-processes:nginx            RUNNING   pid 83, uptime 14 days, 0:47:44
tower-processes:uwsgi            RUNNING   pid 84, uptime 14 days, 0:47:44
tower-processes:wsbroadcast      RUNNING   pid 86, uptime 14 days, 0:47:44
```

awx_task
```bash
supervisorctl -c /etc/supervisord_task.conf status
awx-config-watcher                  RUNNING   pid 98, uptime 14 days, 0:47:31
tower-processes:callback-receiver   RUNNING   pid 100, uptime 14 days, 0:47:31
tower-processes:dispatcher          RUNNING   pid 99, uptime 14 days, 0:47:31
```

No trace on logs

If I restart the container in my swarm orchestrator, all goes well for a moment. If you need more information, i can provide them

AWX Version 17.1.0 (Can't update for now because of the breaking change of the Database, i will try later)
