### ISSUE TITLE
TASK [image_build : Build AWX distribution using container] -  FAILED!

### ISSUE THREAD

**Issue by ReinerNippes** [ansible/awx#3996]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`ansible-playbook -i inventory install.yml` failed building local images

##### ENVIRONMENT
* AWX version: 4.0.0
* AWX install method: docker
* Ansible version:  2.7.10 & 2.8.0
* Operating System: CentOS Linux release 7.6.1810
* Web Browser:

##### STEPS TO REPRODUCE

remove `dockerhub_base=ansible` from inventory
`ansible-playbook -i inventory install.yml`

##### EXPECTED RESULTS

working awx

##### ACTUAL RESULTS

```
TASK [image_build : Build sdist builder image] ************************************************************************************************************************
 [WARNING]: Please specify build.args instead of buildargs. The buildargs option has been renamed and will be removed in Ansible 2.12.

 [WARNING]: Please specify build.path instead of path. The path option has been renamed and will be removed in Ansible 2.12.

 [WARNING]: Please specify build.dockerfile instead of dockerfile. The dockerfile option has been renamed and will be removed in Ansible 2.12.

 [WARNING]: The value of the "source" option was determined to be "build". Please set the "source" option explicitly. Autodetection will be removed in Ansible 2.12.

 [WARNING]: The "force" option will be removed in Ansible 2.12. Please use the "force_source", "force_absent" or "force_tag" option instead, depending on what you
want to force.

[DEPRECATION WARNING]: Param 'force' is deprecated. See the module docs for more information. This feature will be removed in version 2.12. Deprecation warnings can
be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [localhost]

TASK [image_build : Build AWX distribution using container] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm --unsafe-perm --prefix awx/ui ci --no-save awx/ui\n\nUsage: npm <command>\n\nwhere <command> is one of:\n    access, adduser, bin, bugs, c, cache, completion, config,\n    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,\n    help, help-search, i, init, install, install-test, it, link,\n    list, ln, login, logout, ls, outdated, owner, pack, ping,\n    prefix, prune, publish, rb, rebuild, repo, restart, root,\n    run, run-script, s, se, search, set, shrinkwrap, star,\n    stars, start, stop, t, tag, team, test, tst, un, uninstall,\n    unpublish, unstar, up, update, v, version, view, whoami\n\nnpm <cmd> -h     quick help on <cmd>\nnpm -l           display full usage info\nnpm help <term>  search for help on <term>\nnpm help npm     involved overview\n\nSpecify configs in the ini-formatted file:\n    /root/.npmrc\nor on the command line via: npm <command> --key value\nConfig info can be viewed via: npm help config\n\nnpm@3.10.10 /usr/lib/node_modules/npm\nmake: *** [awx/ui/.release_deps_built] Error 1\n", "status": 2}

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=10   changed=2    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```

**Comment by kialam** [comment]
@ReinerNippes what version of npm and node are you running?

**Comment by shanemcd** [comment]
Are you using the 4.0.0 release / tag or did you clone the repo? We recently updated the NPM and Node requirements on `devel`, so if youre tracking the mainline branch consider pinning to a release from https://github.com/ansible/awx/releases

**Comment by ReinerNippes** [comment]
@kialam i don't know. i just want to build and run awx. how to check?
@shanemcd yes. i just cloned the repo. but git checkout 4.0.0 did fix it. just changed the error message.

```
TASK [image_build : Build sdist builder image] *****************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Error building awx_sdist_builder - code: 1, message: The command '/bin/sh -c ln -s /usr/bin/python36 /usr/bin/python3' returned a non-zero code: 1, logs: [u'Step 1/10 : FROM centos:7', u'\\n', u' ---> 9f38484d220f\\n', u'Step 2/10 : RUN yum install -y epel-release', u'\\n', u' ---> Using cache\\n', u' ---> 626807fd83b2\\n', u'Step 3/10 : RUN yum install -y bzip2     gcc-c++     gettext     git     make     python36-setuptools', u'\\n', u' ---> Using cache\\n', u' ---> 168ad7273e0a\\n', u'Step 4/10 : RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -', u'\\n', u' ---> Using cache\\n', u' ---> 4541f23ad08c\\n', u'Step 5/10 : RUN yum install -y nodejs', u'\\n', u' ---> Using cache\\n', u' ---> 6b282a6a755f\\n', u'Step 6/10 : RUN npm set progress=false', u'\\n', u' ---> Using cache\\n', u' ---> 1e9c5aaeed0d\\n', u'Step 7/10 : RUN ln -s /usr/bin/python36 /usr/bin/python3', u'\\n', u' ---> Running in 7083fcd0c757\\n', u\"\\x1b[91mln: failed to create symbolic link '/usr/bin/python3': File exists\\n\\x1b[0m\", u'Removing intermediate container 7083fcd0c757\\n']"}
        to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=9    changed=1    unreachable=0    failed=1
```

**Comment by shanemcd** [comment]
@ReinerNippes Ah right. The upstream centos container image changed and added that symlink to the base python3 package. We have fixed this on devel. Right now you have a couple options:

- Cherry-pick this into your 4.0.0 branch: https://github.com/ansible/awx/commit/4821a949445660efa47879ac22222761aa412836
- Wait until https://github.com/ansible/awx/pull/4005 merges later today and keep tracking devel.

**Comment by ReinerNippes** [comment]
OK. Great. 
Thanks.

**Comment by ReinerNippes** [comment]
@shanemcd 
I assumed that #4005 was merged to devel. but now I got:
```
TASK [image_build : Build sdist builder image] ************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (docker_image) module: build, force_source, source Supported parameters include: api_version, archive_path, buildargs, cacert_path, cert_path, container_limits, debug, docker_host, dockerfile, force, http_timeout, key_path, load_path, name, nocache, path, pull, push, repository, rm, ssl_version, state, tag, timeout, tls, tls_hostname, tls_verify, use_tls"}
        to retry, use: --limit @/root/awx/installer/install.retry

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=9    changed=1    unreachable=0    failed=1

[root@ip-10-105-157-78 installer]# ansible --version
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
``` 
ansible 2.8.0 is required. 
-------
Cherry-picking 4821a94 into your 4.0.0 branch didn't fix the original problem as well. The error message with python link was gone.

```
npm --unsafe-perm --prefix awx/ui ci --no-save awx/ui\n\nUsage: npm <command>\n\nwhere <command> is one of:\n    access, adduser, bin, bugs, c, cache, completion, 
```
