### ISSUE TITLE
HashiVault Token external credential

### ISSUE THREAD

**Issue by rmanibus** [ansible/awx#6158]
##### ISSUE TYPE
 - Feature Idea

It would be useful to have an external credential able to create a hashicorp vault token type with specified capabilities and ttl.
This way we can have a master token in AWX and create short lived token to inject in playbook.

**Comment by rmanibus** [comment]
see #6159

**Comment by mbrancato** [comment]
I think this is better solved by #5076 or similar which would be implementing other auth mechanisms.

This still means AWX would need a long-lived Vault token. These Vault tokens are basically an AuthZ mechanism / session identifier since policies are already attached. It is more secure / preferable to perform AuthN and let Vault assign the correct policies based on the identity. Vault then returns the short-lived vault token to the client. Basically, direct token issuance should always be a last-resort for granting access to Vault.

It may be helpful to read HashiCorp's guide on secure client introduction: https://learn.hashicorp.com/vault/identity-access-management/iam-secure-intro

If AWX wants to dynamically assign tokens, I would suggest a method where Tower signs a short-lived JWT for the playbook run. Vault can then validate the JWT and associate it to a specific identity representative of the playbook.

**Comment by rmanibus** [comment]
I was thinking about running a renew playbook periodically to refresh the awx token.

In fact #5076 solve that part but still does not provide a way to authenticate on vault on the remote host, which is needed to issue a certificate for a webserver directly on the target host for example.
 
Wouldnt jwt require one more step on the host before performing the actual signing operation ?

**Comment by rmanibus** [comment]
What I wanted to achieve is to provide a token in the playbook to sign a key that is located on the host.

maybe having a plug-in that directly allow to interact with the vault PKI and inject a fresh private key and certificate in the playbook would be the way to go ?

also, I'm provisioning new PKI with an ansible playbook (that I run locally on the task container). In that case I think that I really need a token (or jwt) that can be used in the playbook. does #5076 allow to do that by plugin it in a custom credential?

**Comment by mbrancato** [comment]
Once you have a Vault token, you can use (assuming it is authorized) any secret engine in Vault. This includes the PKI engine. The PKI engine has a `/issue/` API that can be used to generate and sign a certificate - it returns the cert and private key but the private key is not stored by Vault.

But the process of doing the initial authentication is where a possible JWT comes into play. And how you get a token is independent of what the token can do, including using the PKI engine.

> What I wanted to achieve is to provide a token in the playbook to sign a key that is located on the host.
> 
> maybe having a plug-in that directly allow to interact with the vault PKI and inject a fresh private key and certificate in the playbook would be the way to go ?
> 
> also, I'm provisioning new PKI with an ansible playbook (that I run locally on the task container). In that case I think that I really need a token (or jwt) that can be used in the playbook. does #5076 allow to do that by plugin it in a custom credential?

**Comment by rmanibus** [comment]
yes of course thanks for the clarification, what I'm not sure about is if the token provided after authentication by #5076 can be plugged into anything (acting as a standalone external auth) or if it live inside the signed ssh plugin in which case the only output available would be a signed certificate.

**Comment by rmanibus** [comment]
if it's the case I think this can be closed.

**Comment by wenottingham** [comment]
Closing per prior comment, please reopen with any new use cases.
