### ISSUE TITLE
(visual adjustment) adjust the way the headers wrap in lists

### ISSUE THREAD

**Issue by dsesami** [ansible/awx#6657]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Currently, on smaller screens, I was always bothered by the way wrapping occurs in lists (the delete button here looks weird)
![Screenshot_20200408_105535](https://user-images.githubusercontent.com/19942822/78799696-7b567c00-7988-11ea-9179-bcd643f18047.png)

I think this would be improved if items did not wrap in such a way that they didn't start with the checkbox on the left. instead, the checkbox would maintain its column, and the delete button would be aligned under "Name", for example.

**Comment by unlikelyzero** [comment]
@dsesami can we retest this? I believe that this has been fixed or could be part of the tables work

**Comment by dsesami** [comment]
wrapping behavior has been improved. I still have issues with the fact that you have to click the search bar, but this was intended.
