### ISSUE TITLE
Invalid search term. 404 error. When trying to view second page of Approval drawer

### ISSUE THREAD

**Issue by pjeanmonod** [ansible/awx#6803]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
404 invalid search when trying to view second page of notification drawer.

##### ENVIRONMENT
* AWX version: 11.0.0
* AWX install method: docker on linux
* Ansible version: 2.9.5
* Operating System: Linux
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Go to second page of Approval notification drawer, get 404 error.

##### EXPECTED RESULTS

the second page of results.

##### ACTUAL RESULTS

Invalid search term entered. GET returned: 404 Invalid page.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/54137368/80013020-1d687f00-84c6-11ea-8cd7-13fa57a427a9.png)

![image](https://user-images.githubusercontent.com/54137368/80013103-41c45b80-84c6-11ea-8078-5e34609b8da3.png)

**Comment by pjeanmonod** [comment]
![image](https://user-images.githubusercontent.com/54137368/80015296-67069900-84c9-11ea-9753-e92650980612.png)

**Comment by pjeanmonod** [comment]
Bug is still unresolved, Closed in error.

**Comment by stefanmcshane** [comment]
Getting a similar error for notifications, that I assume is related. Means we cannot see anything past the first 5 jobs that require approval, which is a bit of a show stopper for production use.

* AWX Version 11.0.0

On opening the notifications drawer, the following is executed:
`GET /api/v2/workflow_approvals/?page=1&page_size=5&order_by=created&status=pending`

On using the pagination buttons, whether it is a number, or an arrow, the following is executed:
`GET /v2/unified_job_templates/?page=2&page_size=5&order_by=created&status=pending`

I'm not a frontend developer, but think this could be related to:
https://github.com/ansible/awx/blob/a34a63ec7f8de22967d1f4d51e574fe1eced5088/awx/ui/client/lib/components/approvalsDrawer/approvalsDrawer.partial.html#L83

**Comment by unlikelyzero** [comment]
Notification Tray Tests:

- Verify that WFJT Approval details are accurate
- Verify that WFJT Link navigates user to correct JT
- User can click Approve button to approve a WFJT
- User can click Deny button to deny a WFJT.
- User can sort Approvals by Created Date
- User can Use Pagination controls to find the 21st Approval WFJT and approve

**Comment by chbmckeown** [comment]
Having the same issue, to confirm was this issue identified and fixed by update?
Unsure from labels/comments...
Thanks

**Comment by pjeanmonod** [comment]
The issue still persists and seems to be common... Has a fix been identified?

**Comment by pjeanmonod** [comment]
For anyone who finds themselves on this thread with the same issue, it has now been fixed in 11.2 as shown below:

commit b1b6af4ad58c56ca50cd38aff4410739bd8243b3
Author: John Mitchell <jmitchel@Johns-MacBook-Pro-46.local>
Date:   Fri Apr 24 15:31:20 2020 -0400

    make sure right endpoint is getting called for notification paginationl
