### ISSUE TITLE
dev environment not able to use inventory plugins from vendored collections

### ISSUE THREAD

**Issue by kdelee** [ansible/awx#6878]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

In dev environment, if we try and run an inventory update for a source that uses a plugin from one of the vendored collections, it says it cannot find it.

##### ENVIRONMENT
* AWX version: X.Y.Z
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
* Ansible version:  X.Y.Z
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Try and run an aws, gce, openstack, rhv, vmware or foreman update in the dev environment

##### EXPECTED RESULTS

finds vendored content and uses it

##### ACTUAL RESULTS

```
[WARNING]:  * Failed to parse /tmp/awx_3_x8wetew_/aws_ec2.yml with auto plugin:
inventory config '/tmp/awx_3_x8wetew_/aws_ec2.yml' specifies unknown plugin
'amazon.aws.aws_ec2'
```

##### ADDITIONAL INFORMATION

1) Update awx/settings/local_settings.py.docker_compose to have INVENTORY_COLLECTIONS_ROOT = '/vendor/inventory_collections'
2) At container build time when /vendor/inventory_collections gets made, we need to make sure it belongs to or is usable by the awx user (edited)

**Comment by shanemcd** [comment]
This should be fixed by a downstream PR, will land here soon-ish

**Comment by kdelee** [comment]
this now works downstream, updating the project to track the fact that this fix needs to be ported to devel

**Comment by AlanCoding** [comment]
this should be ready for verification after next downstream merge finishes

**Comment by MarcoV-git** [comment]
Guys, any idea when a new image will be release to hub.docker with this fix included in the image?

**Comment by geerlingguy** [comment]
I'm trying to demo this on a local environment for an Ansible 101 episode tomorrow, but it seems the current version of the AWX image doesn't have the fix, so I'm getting the same error:

```
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
[WARNING]:  * Failed to parse /tmp/awx_7_mc0wlqrl/aws_ec2.yml with auto plugin:
inventory config '/tmp/awx_7_mc0wlqrl/aws_ec2.yml' specifies unknown plugin
'amazon.aws.aws_ec2'
[WARNING]: Unable to parse /tmp/awx_7_mc0wlqrl/aws_ec2.yml as an inventory
source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by AlanCoding** [comment]
If you are absolutely desperate, I can walk you through how to fix it with your local settings. Otherwise, I don't have a date for the next AWX release.

**Comment by geerlingguy** [comment]
@AlanCoding its okay, I have enough other things to cover, I'll be mentioning this feature and how to use it if you have Tower, just won't show it today.

**Comment by ryanpetrello** [comment]
@MarcoV-git @geerlingguy I _think_ this is probably addressed now via awx 12.0.0 (released yesterday).

**Comment by MarcoV-git** [comment]
@ryanpetrello @AlanCoding I commented accidentally on the newer link to this issue #7109, but it's still broken...

Even with the previous mentioned extension of settings.py:

    [root@testserver1 awx]# grep COLLECTIONS settings.py
    AWX_ANSIBLE_COLLECTIONS_PATHS = '/vendor/awx_ansible_collections'
    [root@testserver1 awx]# podman exec -it awx_awxweb /bin/bash
    bash-4.4$ hostname
    awx
    bash-4.4$ grep COLL /etc/tower/settings.py
    AWX_ANSIBLE_COLLECTIONS_PATHS = '/vendor/awx_ansible_collections'
    bash-4.4$

**Comment by shanemcd** [comment]
@kdelee  I think this can be closed now.

**Comment by kdelee** [comment]
yup

**Comment by danielo515** [comment]
Looks like this problem is coming back, please see  #9321
