### ISSUE TITLE
Failed to get job template details. GET returned status: undefined

### ISSUE THREAD

**Issue by lucaslan** [ansible/awx#704]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When using a machine credential on a template this error apears:
Failed to get job template details. GET returned status: undefined

My machine credential prompts password on launch and I only receive this error if "ask on launch" box is checked!

##### ENVIRONMENT
* AWX version: from 1.0.1.215 to 1.0.1.229 
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: RHEL7
* Web Browser: Firefox/Google Chrome

##### STEPS TO REPRODUCE

Go to CREDENTIALS and create a new machine credential, remember to ask password on launch.
Now edit the Demo Job Template to use your brand new credential

##### EXPECTED RESULTS

Run jobs asking credentials on launch

##### ACTUAL RESULTS

![awx_template](https://user-images.githubusercontent.com/24614153/33184354-4c45f308-d063-11e7-9415-d7504ef50bb0.PNG)

**Comment by AlanCoding** [comment]
possible fallout related to #352, where API work has been done, but UI has not updated.

**Comment by tidypete** [comment]
have you resolved this? I am having the same issue on AWX 1.0.2.301

**Comment by oguzy** [comment]
Already installed the current version, build locally, using awx-1.0.2.303.tar.gz and choosing prompt at the limit part, causing the same error.

**Comment by kuklis** [comment]
I just noticed this problem on a new install of 1.0.2-307
I recall some weird behavior on 1.0.2-293 but mostly it works. Starting to downgrade...

**Comment by mkempster22** [comment]
Fixed in .327

**Comment by agaffney** [comment]
I've updated my `awx_task` and `awx_web` containers to `1.0.2.327` (well, `latest`, which Docker tells me was updated 18 hours ago), and this issue still seems to be present.

```
$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ansible/awx_task    1.0.2.327           7798f2119f45        18 hours ago        1.06GB
ansible/awx_task    latest              7798f2119f45        18 hours ago        1.06GB
ansible/awx_web     1.0.2.327           fb0919972013        18 hours ago        1.04GB
ansible/awx_web     latest              fb0919972013        18 hours ago        1.04GB
```

**Comment by mkempster22** [comment]
@agaffney  How did you update?

This is my way (Not sure this is the best way so be aware, also I have a locally installed postgres rather than a container)

./upgradeawx.sh 
~~~~
#!/bin/bash

service docker start

docker stop memcached rabbitmq awx_web awx_task
docker rm memcached rabbitmq awx_web awx_task


docker pull ansible/awx_task
docker pull ansible/awx_web
docker pull memcached
docker pull rabbitmq

cd /opt/ansible/awx

git pull

cd /opt/ansible/awx/installer/

./startawx.sh
~~~~

**Comment by agaffney** [comment]
I did an explicit `docker pull` on the `ansible/awx_task` and `ansible/awx_web` images and then re-ran the install playbook. The running containers match the images with the tag `1.0.2.327`.

```
agaffney@awx:~/awx/installer$ sudo docker inspect awx_task | grep Image | head -n 1
        "Image": "sha256:7798f2119f452a7334e35f5904e3fb84b4a32cf6bce2f6faa9cc9fb0fce645f5",
agaffney@awx:~/awx/installer$ sudo docker inspect awx_web | grep Image | head -n 1
        "Image": "sha256:fb09199720136036203b81db9ef3138c78ab234bea1d1313b19749539595f6f1",
```

**Comment by mkempster22** [comment]
Not sure how important it is but did you do a git pull on your repo before running the playbook again?

Previously I couldnt launch jobs etc. without getting the error but now all seems to be fixed

**Comment by agaffney** [comment]
After doing a `git pull`, an explicit `docker stop/rm` on the `awx_task` and `awx_web` containers, and re-running the installer playbook, it now seems to be working properly. I have no idea why that would actually work, since I'm using the public images and the git update didn't change anything with the installer playbook.

**Comment by mkempster22** [comment]
Yeah i don't know all that much when it comes to how docker containers work but I've had issues doing stuff with them and have usually found completely removing them (assuming you have persistent data) and remaking them fixes most issues

**Comment by agaffney** [comment]
It's possible that my problem was cached Javascript. After the second attempt to "upgrade", I also used Ctrl-Shift-R to clear the cache and refresh.

**Comment by mrtsniper** [comment]
Hi
I encountered this issue and fix it by changing the awx_web and awx_tasks volumes  from 
{{ project_data_dir }}:/var/lib/awx/projects:rw
to 
{{ project_data_dir }}:/var/lib/awx/projects:z

**Comment by jaredevantabor** [comment]
This should be fixed now. Ping me if I need to reopen it.

**Comment by d4rkd0s** [comment]
I'm still having this issue on awx 1.0.8 downloaded and installed today with docker ce on CentOS 7

**Comment by d4rkd0s** [comment]
Okay oddly, after waiting a few extra minutes. It worked. I waited about 10 minutes, did my first login attempt. No luck got the error `Failed to get job template details. GET returned status: undefined` but then after waiting 1-2 mins and trying to login again, it worked! :confused:
