### ISSUE TITLE
Notifications Revert to Success (Off) and Failure (On)

### ISSUE THREAD

**Issue by jmarci** [ansible/awx#711]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Notifications revert to success (Off) and failure (On) on both templates and projects.

##### ENVIRONMENT

* AWX version: 1.0.1.229
* AWX install method: docker on linux
* Ansible version:  2.4.1.0
* Operating System: CentOS7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

1) Create notification(s)
2) Toggle success and/or failure settings off/on

##### EXPECTED RESULTS

To save to desired settings

##### ACTUAL RESULTS
Reverting to Success (Off) and Failure (On)

![image](https://user-images.githubusercontent.com/20398085/33230662-dd202abe-d1a4-11e7-883d-9888754631f7.png)

![image](https://user-images.githubusercontent.com/20398085/33230664-e26bc136-d1a4-11e7-9eac-e0f3a184cb2b.png)

**Comment by AlanCoding** [comment]
I can not reproduce this by creating a notification template, and then toggling the buttons for a job template. It saves these new states, as I would expect. Could you open the Chrome debugger (right click, "inspect") and tell us what you see in the console and network tabs as you reproduce this?

**Comment by jmarci** [comment]
Hi Alan,

Just did fresh default install of latest build and getting same thing, reverting back to success (Off) and failure (On).

![image](https://user-images.githubusercontent.com/20398085/33315574-4cd39148-d3ee-11e7-92c2-7dbdc77362d5.png)

![image](https://user-images.githubusercontent.com/20398085/33315592-57e5d492-d3ee-11e7-8fbc-b8356b662e7e.png)
![image](https://user-images.githubusercontent.com/20398085/33315598-5c7ef1a0-d3ee-11e7-83c8-d8d3cceb74fe.png)

**Comment by boagg** [comment]
Hi Alan, 

Same problem for me, choices are never saved 

Version : <  AWX 1.0.1.229  >

**Comment by Gamoth** [comment]
Hi,
Same problem for me, choices are never saved. This is a docker install also.

Version : < AWX 1.0.1.240 >

**Comment by truki** [comment]
Hi Alan, same problem for me with latest build installed over docker.

**Comment by jaredevantabor** [comment]
Minor issue here was caused by some fallout from the AngularJS upgrade to 1.6.

**Comment by jaredevantabor** [comment]
moving to test

EDIT: already was moved to test...

**Comment by mikecurrancs** [comment]
We installed the latest versions of Docker 2 days ago, and looking over the source code, I see the changes you committed for test. However I still see the same behavior inside the running docker images. Do I need to redeploy from source instead of pulling the latest image?

**Comment by innossh** [comment]
I tried the latest docker images `1.0.2.303` and this issue was fixed, I guess. 👍
However, the Slack notification is still not working for job completion (success or failure). I'm not sure the reason, but I think this issue is related to not only UI.
@matburt Could you reopen this one? https://github.com/ansible/awx/issues/753 or I'll create the new issue if it's needed.

**Comment by sparkacus** [comment]
I also have what I think is the same issue.

Originally before upgrading to the latest version I couldn't enable notifications on templates in the UI (I could adjust the on/off toggle but the changes were not saved). That issue is now fixed but template success/failure hipchat notifications aren't working for me.

I know the hipchat notification setup is correct because the notification tests work.

**Comment by apollo13** [comment]
Same here, SCM notifications work though, but job notifications still do not send anything.

**Comment by matburt** [comment]
These seem like new issues and not related to the original issue.
