### ISSUE TITLE
awx.awx collection 14.0.0 build with wrong version number

### ISSUE THREAD

**Issue by kenchrcum** [ansible/awx#7870]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx.awx collection version 14.0.0 was built with version 0.0.1-devel so every time connecting to an AWX instance we get the warning `[WARNING]: You are running collection version 0.0.1-devel` connecting to tower version 14.0.0

##### ENVIRONMENT
* AWX version: 14.0.0
* AWX install method: docker on linux
* Ansible version:  2.9.11

##### STEPS TO REPRODUCE

Freshly install awx.awx collection version 14.0.0 from ansible-galaxy.
`ansible-galaxy collection install awx.awx:14.0.0 --force`

##### EXPECTED RESULTS

There should be no warning working with an AWX installation at version 14.0.0

##### ACTUAL RESULTS

`[WARNING]: You are running collection version 0.0.1-devel`

##### ADDITIONAL INFORMATION

From awx.awx collection README: `0.0.1-devel is the version you should see if installing from source, which is intended for development and expected to be unstable.`
Collection was installed via ansible-galaxy:
```
$ ansible-galaxy collection install awx.awx:14.0.0 --force
Process install dependency map
Starting collection install process
Installing 'awx.awx:14.0.0' to '/home/user/.ansible/collections/ansible_collections/awx/awx'

```

**Comment by ryanpetrello** [comment]
@AlanCoding @beeankha @squidboylan you all have any idea what's up here?

**Comment by kdelee** [comment]
did `make build_collection` and then installed, it is now correctly versioned. Thanks!

```
$ ansible-galaxy collection install awx_collection_build/awx-awx-14.0.0.tar.gz 
Process install dependency map
Starting collection install process
Installing 'awx.awx:14.0.0' to '/home/elijah/.ansible/collections/ansible_collections/awx/awx'
```

**Comment by AlanCoding** [comment]
That's good, but I think this is still waiting for 14.1.0 to go out the door until it's fixed in the released version.

https://github.com/ansible/awx/blob/devel/CHANGELOG.md

That's still marked as TBD, but when it does happen, we should still be sure to have a look at what it produces.

**Comment by kdelee** [comment]
oops yeah you are right the released version still not doing the right thing, will re-open til what we get from ansible galaxy reports right version

```
 ansible-galaxy collection install awx.awx
Process install dependency map
Starting collection install process
Installing 'awx.awx:14.0.0' to '/home/elijah/.ansible/collections/ansible_collections/awx/awx'
 elijah  (e) py36venv  ~  sfw  ansible  ansible-playbook -i localhost foo2.yml 
[WARNING]: Unable to parse /home/elijah/sfw/ansible/localhost as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
PLAY [localhost] ********************************************************************************************************************************************
TASK [tower_meta] *******************************************************************************************************************************************
ok: [localhost]
TASK [Show details about the collection] ********************************************************************************************************************
ok: [localhost] => 
  result:
    changed: false
    failed: false
    name: awx
    namespace: awx
    prefix: awx.awx
    version: 0.0.1-devel
PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by kdelee** [comment]
can't verify til next release gets pushed to ansible galaxy

**Comment by ryanpetrello** [comment]
I think this is done, @kdelee @AlanCoding:

```shell
~ ansible-galaxy collection install awx.awx
Process install dependency map
Starting collection install process
Installing 'awx.awx:14.1.0' to '/home/ryanpetrello/.ansible/collections/ansible_collections/awx/awx'
~ ack 14.1.0 ~/.ansible/collections/ansible_collections/awx/awx
/home/ryanpetrello/.ansible/collections/ansible_collections/awx/awx/plugins/module_utils/tower_api.py
17:    _COLLECTION_VERSION = "14.1.0"

/home/ryanpetrello/.ansible/collections/ansible_collections/awx/awx/MANIFEST.json
23:  "version": "14.1.0",
```

**Comment by kenchrcum** [comment]
No warnings on 14.1.0. Thank you all for working on this!

**Comment by ashleyghooper** [comment]
This seems to be happening again for 21.0.0:

```
Installing 'awx.awx:21.0.0' to '/root/.ansible/collections/ansible_collections/awx/awx'
$ ansible-playbook config.yml -e awx_env=${ENV}
PLAY [Configure AWX] ***********************************************************
TASK [Configure AWX LDAP settings] *********************************************
[WARNING]: You are running collection version 0.0.1-devel but connecting to AWX
version 19.5.0
changed: [localhost]
```

Switching to 19.4.0 fixed it.

**Comment by AlanCoding** [comment]
We have a new issue for that https://github.com/ansible/awx/issues/12060

This issue was for the first time we broke it.
