### ISSUE TITLE
[ui_next] Favicon is missing

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8618]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
No favicon!

##### ENVIRONMENT
* AWX version: b338da40c534d1b2809b5426b61f13eff7770434
* AWX install method: `npm install`

##### ADDITIONAL INFORMATION
![Screen Shot 2020-11-18 at 11 14 14 AM](https://user-images.githubusercontent.com/12446869/99556189-361f1180-298f-11eb-8dcc-1df88dbd8f05.png)

**Comment by jakemcdermott** [comment]
There's a good chance this is addressed by: https://github.com/ansible/awx/pull/9369#issue-576684262

**Comment by tiagodread** [comment]
@jakemcdermott  This is not fixed yet on development environment (3001) and production build (8043)

![image](https://user-images.githubusercontent.com/12464858/109864592-c97c0a00-7c41-11eb-8775-dda312c6390c.png)

**Comment by jbradberry** [comment]
The issue almost certainly is the nginx rewrite rule that adds slashes to the ends of our urls, i.e.

```
awx_1_1     | awx-uwsgi stdout | 2021-05-12 14:57:20,482 WARNING  [e6742792] django.request Not Found: /favicon.ico/
```

`/favicon.ico/`, not `/favicon.ico`

**Comment by jbradberry** [comment]
Digging around, relevant files may be:

- awx-operator
  - roles/installer/templates/tower_config.yaml.j2
    - has `location /favicon.ico` directive

- awx
  - tools/docker-compose/nginx.vh.default.conf
    - does not have `location /favicon.ico` directive
  - tools/docker-compose/ansible/roles/sources/templates/nginx.conf.j2
    - has `location /favicon.ico` directive

- tower-packaging
  - setup_openshift/roles/kubernetes/templates/configmap.yml.j2
    - has `location /favicon.ico` directive
  - setup/roles/nginx/templates/nginx.conf
    - has `location /favicon.ico` directive

It's not 100% clear to me at the moment if the Nginx files that _do_ have the `location /favicon.ico` directive sufficiently avoid this problem, or if there is interaction between the directives that still allows this to occur.

**Comment by jbradberry** [comment]
I have confirmed that an instance deployed via YOLO does the right thing with a request for `/favicon.ico`.

**Comment by jbradberry** [comment]
#10205 should fix this for the development environment, though since the underlying issue is a permanent redirect you'll have to do extra steps to clear that redirect out of your browser.  It seems like choosing "Forget this site" and restarting my browser was sufficient in Firefox.

**Comment by tiagodread** [comment]
Yolo build loading the favicon correctly
![image](https://user-images.githubusercontent.com/12464858/119568107-81254180-bd83-11eb-8ae3-4f5256d891bc.png)
