### ISSUE TITLE
Unable to create schedule for Workflow Job Template.

### ISSUE THREAD

**Issue by tvigers** [ansible/awx#897]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

Unable to create schedule for Workflow Job Template. "Field is not allowed for use in workflows."

##### ENVIRONMENT
* AWX version: 1.0.2.285-1.0.2.298
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: RHEL7.4
* Web Browser: 
    - Google Chrome 63.0.3239.84 (Official Build) (64-bit)
    - Firefox ESR 52.5.1 (64-bit)

##### STEPS TO REPRODUCE

1. Click on Schedule icon for Workflow Job Template;
2. Fill out all of the schedule fields;
3. Save schedule.

##### EXPECTED RESULTS

Schedule to save without error.
##### ACTUAL RESULTS

"ERROR!

Field is not allowed for use in workflows."

![image](https://user-images.githubusercontent.com/6075327/34429301-3369d54c-eca2-11e7-8482-ce01730f212d.png)

Also a 400 Bad Request response is received:

![screenshot from 2017-12-29 15-13-35](https://user-images.githubusercontent.com/6075327/34429511-d79cf4c6-eca4-11e7-8bc7-7db7f8ddbbd0.jpg)

`172.17.0.1 - - [29/Dec/2017:04:07:06 +0000] "GET /api/v2/workflow_job_templates/80/ HTTP/1.1" 200 3272 "https://tower.example.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" "172.27.128.205"
[pid: 28|app: 0|req: 306/783] 172.17.0.1 () {52 vars in 2256 bytes} [Fri Dec 29 04:07:06 2017] GET /api/v2/workflow_job_templates/80/ => generated 3272 bytes in 114 msecs (HTTP/1.1 200) 9 headers in 270 bytes (1 switches on core 0)
2017-12-29 04:08:23,086 WARNING  awx.api.generics status 400 received by user test attempting to access /api/v2/workflow_job_templates/80/schedules/ from 172.17.0.1
[pid: 28|app: 0|req: 307/784] 172.17.0.1 () {56 vars in 2387 bytes} [Fri Dec 29 04:08:23 2017] POST /api/v2/workflow_job_templates/80/schedules/ => generated 144 bytes in 64 msecs (HTTP/1.1 400) 9 headers in 264 bytes (1 switches on core 0)
172.17.0.1 - - [29/Dec/2017:04:08:23 +0000] "POST /api/v2/workflow_job_templates/80/schedules/ HTTP/1.1" 400 144 "https://tower.example.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" "172.27.128.205"
2017-12-29 04:12:19,646 WARNING  awx.api.generics status 400 received by user test attempting to access /api/v2/workflow_job_templates/80/schedules/ from 172.17.0.1
[pid: 28|app: 0|req: 308/785] 172.17.0.1 () {56 vars in 2387 bytes} [Fri Dec 29 04:12:19 2017] POST /api/v2/workflow_job_templates/80/schedules/ => generated 144 bytes in 70 msecs (HTTP/1.1 400) 9 headers in 264 bytes (1 switches on core 0)
172.17.0.1 - - [29/Dec/2017:04:12:19 +0000] "POST /api/v2/workflow_job_templates/80/schedules/ HTTP/1.1" 400 144 "https://tower.example.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" "172.27.128.205"
`

##### ADDITIONAL INFORMATION

- Using nginx on the docker host to do ssl termination;
- Haven't been able to test on anything higher than 1.0.2.298 due to #891;
- Using Extra Variables in the Workflow Template but error still occurs when not using Extra Variables;

This was working at one point as I had this same configuration about a month ago but unable to determine what version exactly was being used, but I would imagine it was 1.0.1.xx

**EDIT:** Was able to get this working in 1.0.1.203.

**Comment by tvigers** [comment]
Still unable to get this working in 1.0.2.327, tested after upgrading to 1.0.2.327 to fix the issue in #891.

**Comment by ElliotGo** [comment]
@tvigers I have the same issue in AWX 1.0.2.356 docker environment.
Schedule for a single job works fine.

**Comment by ElliotGo** [comment]
@mabashian can you please take a look at this issue?

**Comment by matburt** [comment]
This should be fixed here: https://github.com/ansible/awx/pull/979

**Comment by ElliotGo** [comment]
@matburt Still getting the same error in AWX 1.0.2.79 docker environment, can you please take a look?

**Comment by matburt** [comment]
`1.0.2.79` is very old... update to a new version and try again.
