### ISSUE TITLE
Unable to delete any template

### ISSUE THREAD

**Issue by madeinoz67** [ansible/awx#975]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - UI

##### SUMMARY
Deleting a Template fails to remove template

##### ENVIRONMENT
* AWX version: 1.0.2.370
* AWX install method: docker on linux
* Ansible version:  2.4.2.0
* Operating System: Server: Centos 7, client: MacOS 10.13.2
* Web Browser: Safari 11.0.2

##### STEPS TO REPRODUCE

1. from the template page the delete button (rubbish bin) is pushed on the template to be deleted
2. the delete confirmation dialog appears asking for confirmation
3. "Delete" is pushed to confirm deletion.
4. the Waiting spins briefly in the bottom right of screen 
5. returns to template screen and template is not removed 

##### EXPECTED RESULTS

When the delete is confirmed the template should be removed from the template screen 

##### ACTUAL RESULTS

the template is not removed from the template screen

##### ADDITIONAL INFORMATION

jsconsole error log

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (5, line 0)
[Error] Can't find variable: string
http://nms-ans01/static/js/app.ffa3c911d0e70695add5.js:29 – "Possibly unhandled rejection: {\"line\":29,\"column\":145697,\"sourceURL\":\"http://nms-ans01/static/js/app.ffa3c911d0e70695add5.js\"}"
	(anonymous function) (vendor.bd5b7932827855e6a213.js:570:93569)
	processChecks (vendor.bd5b7932827855e6a213.js:570:134821)
	$digest (vendor.bd5b7932827855e6a213.js:570:146078)
	$apply (vendor.bd5b7932827855e6a213.js:570:148862)
	done (vendor.bd5b7932827855e6a213.js:570:101129)
	completeRequest (vendor.bd5b7932827855e6a213.js:570:106031)
	onload (vendor.bd5b7932827855e6a213.js:570:106797)'

**Comment by lucasreed** [comment]
Getting the same error in chrome. Here's the output from web tools console formatted. First error is a 404 on the api DELETE request, which is strange since it's definitely there. Second is the same javascript error reported by @madeinoz67 :
```
VM2833:1 DELETE https://awx.digitalsmithsdev.net/api/v2/unified_job_templates/5/ 404 (Not Found)
  | (anonymous) | @ | VM2833:1
-- | -- | -- | --
  | (anonymous) | @ | vendor.bd5b793….js:570
  | sendReq | @ | vendor.bd5b793….js:570
  | serverRequest | @ | vendor.bd5b793….js:570
  | processQueue | @ | vendor.bd5b793….js:570
  | (anonymous) | @ | vendor.bd5b793….js:570
  | $digest | @ | vendor.bd5b793….js:570
  | $apply | @ | vendor.bd5b793….js:570
  | (anonymous) | @ | vendor.bd5b793….js:570
  | dispatch | @ | vendor.bd5b793….js:29
  | elemData.handle | @ | vendor.bd5b793….js:29
```
```
vendor.bd5b7932827855e6a213.js:570 ReferenceError: string is not defined
    at app.ffa3c911d0e70695add5.js:29
    at processQueue (vendor.bd5b7932827855e6a213.js:570)
    at vendor.bd5b7932827855e6a213.js:570
    at Scope.$digest (vendor.bd5b7932827855e6a213.js:570)
    at Scope.$apply (vendor.bd5b7932827855e6a213.js:570)
    at done (vendor.bd5b7932827855e6a213.js:570)
    at completeRequest (vendor.bd5b7932827855e6a213.js:570)
    at XMLHttpRequest.xhr.onload (vendor.bd5b7932827855e6a213.js:570) "Possibly unhandled rejection: {}"
```

Edit: added the DELETE request failure message
Edit 2: Confirmed it's not properly issuing the DELETE api call because it's still there in the api backend as well. Temp workaround for me was to navigate to `/api/v2/job_templates/5/` and issue the DELETE request there. I should also mention that other DELETE requests outside of the template menu appear to work. I can successfully remove a project and inventory from the UI.

**Comment by jaredevantabor** [comment]
@jlmitch5 is this fallout from the expanded list feature landing?

**Comment by tidypete** [comment]
Has this issue been resolved yet? I am getting the same error when trying to delete templates

**Comment by mabashian** [comment]
This issue should be resolved by #990

**Comment by tidypete** [comment]
Still unable to delete any templates. 

ERROR:

Call to /api/v2/unified_job_templates/24 failed. DELETE returned status: 404. The requested resource could not be found.

ENVIRONMENT

AWX version: 1.0.2.372
AWX install method: docker on linux
Ansible version: 2.4.2.0
Operating System: Server: Centos 7

**Comment by saiprasad169** [comment]
in Inventory file please don't edit the rabbitmq password keep it as default

**Comment by saiprasad169** [comment]
> Still unable to delete any templates.
> 
> ERROR:
> 
> Call to /api/v2/unified_job_templates/24 failed. DELETE returned status: 404. The requested resource could not be found.
> 
> ENVIRONMENT
> 
> AWX version: 1.0.2.372
> AWX install method: docker on linux
> Ansible version: 2.4.2.0
> Operating System: Server: Centos 7

This issue basically happen for rabbitmq container where it throws error credentials

**Comment by saiprasad169** [comment]
> > Still unable to delete any templates.
> > ERROR:
> > Call to /api/v2/unified_job_templates/24 failed. DELETE returned status: 404. The requested resource could not be found.
> > ENVIRONMENT
> > AWX version: 1.0.2.372
> > AWX install method: docker on linux
> > Ansible version: 2.4.2.0
> > Operating System: Server: Centos 7
> 
> This issue basically happen for rabbitmq container where it throws error credentials

you can keep the default password for rabbitmq it will work fine and please re-deploy the container or restart it
